# Generated by Django 3.1.7 on 2021-03-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_text', models.CharField(max_length=200)),
                ('punchline_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JokeBotAI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knock_knock', models.BooleanField(default=False)),
                ('setup', models.BooleanField(default=False)),
                ('new_setup', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200)),
                ('message_nametag', models.CharField(max_length=50)),
                ('message_date', models.DateTimeField(auto_now_add=True, verbose_name='date sent')),
            ],
        ),
    ]
