# Generated by Django 3.1.7 on 2021-03-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokebotai',
            name='current_joke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jokebot.joke'),
        ),
    ]
