# Generated by Django 3.1.7 on 2021-03-07 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokebotai',
            name='current_joke',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='jokebot.joke'),
            preserve_default=False,
        ),
    ]
