# Generated by Django 3.1.7 on 2021-03-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_text', models.CharField(max_length=200)),
                ('punchline_text', models.CharField(max_length=200)),
            ],
        ),
    ]
