# Generated by Django 3.1.7 on 2021-03-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0002_jokebotai_current_joke'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokebotai',
            name='gave_knock_knock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jokebotai',
            name='gave_setup',
            field=models.BooleanField(default=False),
        ),
    ]
