# Generated by Django 3.1.7 on 2021-03-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0002_joke'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(max_length=200)),
                ('message_nametag', models.CharField(max_length=50)),
            ],
        ),
    ]
