# Generated by Django 3.1.7 on 2021-03-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0003_auto_20210307_0340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
