# Generated by Django 3.1.7 on 2021-03-04 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date sent'),
            preserve_default=False,
        ),
    ]
