# Generated by Django 3.1.7 on 2021-03-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0004_message_message_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeBotAI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jokebot.greeting')),
            ],
        ),
    ]
