# Generated by Django 3.1.7 on 2021-03-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0005_jokebotai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jokebotai',
            name='greeting',
        ),
        migrations.AddField(
            model_name='jokebotai',
            name='heard_knock_knock',
            field=models.BooleanField(default=False),
        ),
    ]
