# Generated by Django 3.1.7 on 2021-03-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0007_jokebotai_heard_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokebotai',
            name='heard_knock_knock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jokebotai',
            name='heard_setup',
            field=models.IntegerField(default=0),
        ),
    ]
