# Generated by Django 3.1.7 on 2021-03-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0009_auto_20210307_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='jokebotai',
            name='new_punchline',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jokebotai',
            name='new_setup',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
