# Generated by Django 3.1.7 on 2021-03-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokebot', '0010_auto_20210307_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jokebotai',
            name='new_punchline',
        ),
    ]
